forlist.cmo :
forlist.cmx :
main.cmo : \
    origami.cmi \
    forlist.cmo
main.cmx : \
    origami.cmx \
    forlist.cmx
origami.cmo : \
    forlist.cmo \
    origami.cmi
origami.cmx : \
    forlist.cmx \
    origami.cmi
